#!/usr/bin/env bash
#
# Tests for the Joomla container clone helpers in src/octojoom.
#
# The helpers have no user interaction, so they are extracted from the script
# and run against fixtures generated by the script's own joomlaContainer
# template. Run from anywhere:
#
#   bash tests/test-clone.sh
#
# Needs bash 4+, sed, grep, awk and diff. No docker or whiptail required.
#
# SC2015: "A && pass || fail" is the intended check idiom (pass never fails).
# SC2016: single quoted ${...} are literal compose variables we grep for.
# SC2034: the VDM_* values are read by the extracted joomlaContainer template.
# shellcheck disable=SC2015,SC2016,SC2034

set -u

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="${TEST_DIR}/../src/octojoom"
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

PASSED=0
FAILED=0

pass() {
  PASSED=$((PASSED + 1))
  echo "ok   - $1"
}

fail() {
  FAILED=$((FAILED + 1))
  echo "FAIL - $1"
  [ -n "${2:-}" ] && echo "       $2"
}

# extract one function definition from the script
extract_function() {
  awk -v name="$1" '$0 ~ "^function "name"\\(\\) \\{$" {p=1} p {print} p && /^}$/ {p=0; exit}' "${SCRIPT}"
}

for fn in getYMLine1 getYMLine2 getYMLine3 joomlaContainer \
  getJoomlaEnvSuffixes getJoomlaComposeIdentity rewriteJoomlaComposeIdentity \
  getJoomlaConfigValue cloneJoomlaConfiguration cloneContainerEnvVariables \
  cloneContainerEnvFile removeContainerEnvVariables; do
  src=$(extract_function "${fn}")
  if [ -z "${src}" ]; then
    echo "FAIL - function ${fn} not found in ${SCRIPT}"
    exit 1
  fi
  eval "${src}"
done

###############################################################################
# fixture generator: builds a docker-compose.yml the way joomla__TRuST__setup does
# $1 key  $2 env key  $3 sub-domain  $4 domain
# $5 mailcatcher (true/false)  $6 secure (true/false)  $7 puid (true/false)
# $8 php.ini (true/false)  $9 entrypoint (true/false)  $10 named volumes (true/false)
# $11 (optional) php.ini project folder (default: the key)
gen_compose() {
  local mail="${5:-false}" secure="${6:-false}" puid="${7:-false}"
  local php="${8:-false}" entry="${9:-false}" named="${10:-false}"
  local php_folder="${11:-$1}"
  local middlewares='joomla-security'
  VDM_KEY="$1"
  VDM_ENV_KEY="$2"
  VDM_SUBDOMAIN="$3"
  VDM_DOMAIN="$4"
  VDM_J_REPO='joomla'
  VDM_JV='5.3'
  VDM_TRAEFIK_GATEWAY='traefik_webgateway'
  VDM_PUID=''
  VDM_PGID=''
  ${puid} && VDM_PUID=1000 && VDM_PGID=1000
  VDM_JOOMLA_SECURE_LABELS=''
  VDM_PHPMYADMIN_SECURE_LABELS=''
  VDM_EXTRA_CONTAINER_STUFF=''
  VDM_EXTRA_JOOMLA_ENV=''
  VDM_VOLUMES=''
  if ${secure}; then
    VDM_JOOMLA_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.joomla${VDM_KEY}.entrypoints=websecure\"")
    VDM_JOOMLA_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.joomla${VDM_KEY}.tls.certresolver=vdmresolver\"")
    VDM_JOOMLA_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.joomla${VDM_KEY}.service=joomla${VDM_KEY}\"")
    VDM_JOOMLA_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.joomla${VDM_KEY}.middlewares=${middlewares}\"")
    VDM_JOOMLA_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.services.joomla${VDM_KEY}.loadbalancer.server.port=80\"")
    VDM_PHPMYADMIN_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.phpmyadmin${VDM_KEY}.entrypoints=websecure\"")
    VDM_PHPMYADMIN_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.phpmyadmin${VDM_KEY}.tls.certresolver=vdmresolver\"")
    VDM_PHPMYADMIN_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.phpmyadmin${VDM_KEY}.service=phpmyadmin${VDM_KEY}\"")
    VDM_PHPMYADMIN_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.phpmyadmin${VDM_KEY}.middlewares=${middlewares}\"")
    VDM_PHPMYADMIN_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.services.phpmyadmin${VDM_KEY}.loadbalancer.server.port=80\"")
  fi
  if ${named}; then
    VDM_JOOMLA_VOLUMES_MOUNT=$(getYMLine3 "- ${VDM_KEY,,}_web:/var/www/html")
    VDM_DB_VOLUMES_MOUNT=$(getYMLine3 "- ${VDM_KEY,,}_db:/var/lib/mysql")
    VDM_VOLUMES='volumes:'
    VDM_VOLUMES+=$(getYMLine1 "${VDM_KEY,,}_web:")
    VDM_VOLUMES+=$(getYMLine1 "${VDM_KEY,,}_db:")
  else
    VDM_JOOMLA_VOLUMES_MOUNT=$(getYMLine3 "- \"\${VDM_PROJECT_PATH}/${VDM_KEY}/joomla:/var/www/html\"")
    VDM_DB_VOLUMES_MOUNT=$(getYMLine3 "- \"\${VDM_PROJECT_PATH}/${VDM_KEY}/db:/var/lib/mysql\"")
  fi
  if ${mail}; then
    VDM_EXTRA_CONTAINER_STUFF=$(getYMLine1 "mailcatcher${VDM_KEY}:")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine2 "image: schickling/mailcatcher")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine2 "container_name: mailcatcher${VDM_KEY}")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine2 "restart: unless-stopped")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine2 "networks:")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- traefik")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine2 "labels:")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "# mailcatcher")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.enable=true\"")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.http.routers.mailcatcher${VDM_KEY}.rule=Host(\`${VDM_SUBDOMAIN}mail.${VDM_DOMAIN}\`)\"")
    if ${secure}; then
      VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.http.routers.mailcatcher${VDM_KEY}.entrypoints=websecure\"")
      VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.http.routers.mailcatcher${VDM_KEY}.tls.certresolver=vdmresolver\"")
    fi
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.http.routers.mailcatcher${VDM_KEY}.service=mailcatcher${VDM_KEY}\"")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.http.services.mailcatcher${VDM_KEY}.loadbalancer.server.port=1080\"")
    VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_SMTP_HOST=mailcatcher${VDM_KEY}:1025")
  fi
  # auto deploy values
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_DB_TYPE=\${VDM_${VDM_ENV_KEY^^}_JOOMLA_DB_TYPE}")
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_DB_PREFIX=\${VDM_${VDM_ENV_KEY^^}_JOOMLA_DB_PREFIX}")
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_SITE_NAME=\${VDM_${VDM_ENV_KEY^^}_JOOMLA_SITE_NAME}")
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_ADMIN_PASSWORD=\${VDM_${VDM_ENV_KEY^^}_JOOMLA_ADMIN_PASSWORD}")
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_EXTENSIONS_URLS=\${VDM_${VDM_ENV_KEY^^}_EXTENSIONS_URLS}")
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_CLI_COMMANDS=\${VDM_${VDM_ENV_KEY^^}_CLI_COMMANDS}")
  if ${php}; then
    VDM_JOOMLA_VOLUMES_MOUNT+=$(getYMLine3 "- \"\${VDM_PROJECT_PATH}/${php_folder}/php.ini:/var/www/html/php.ini\"")
  fi
  if ${entry}; then
    VDM_JOOMLA_VOLUMES_MOUNT+=$(getYMLine3 "- \"\${VDM_PROJECT_PATH}/${VDM_KEY}/entrypoint.sh:/entrypoint.sh\"")
  fi
  joomlaContainer
}

# run one rewrite case and compare with a freshly generated file
# $1 name  $2..$11 see gen_compose for the old values  $12 new key  $13 new env  $14 new sub  $15 new domain
rewrite_case() {
  local name="$1"
  local old_key="$2" old_env="$3" old_sub="$4" old_domain="$5"
  local mail="$6" secure="$7" puid="$8" php="$9" entry="${10}" named="${11}"
  local new_key="${12}" new_env="${13}" new_sub="${14}" new_domain="${15}"
  local php_folder="${16:-}"
  local dir="${WORK}/${name}"
  local rc
  mkdir -p "${dir}"
  gen_compose "${old_key}" "${old_env}" "${old_sub}" "${old_domain}" "${mail}" "${secure}" "${puid}" "${php}" "${entry}" "${named}" "${php_folder:-$old_key}" >"${dir}/old.yml"
  gen_compose "${new_key}" "${new_env}" "${new_sub}" "${new_domain}" "${mail}" "${secure}" "${puid}" "${php}" "${entry}" "${named}" "${php_folder:-$new_key}" >"${dir}/expected.yml"
  rewriteJoomlaComposeIdentity "${dir}/old.yml" "${dir}/got.yml" "${old_key}" "${new_key}" "${old_env}" "${new_env}" "${old_sub}" "${new_sub}" "${old_domain}" "${new_domain}"
  rc=$?
  if [ "${rc}" -ne 0 ]; then
    fail "rewrite ${name}: returned ${rc}"
  elif diff -u "${dir}/expected.yml" "${dir}/got.yml" >"${dir}/diff.txt"; then
    pass "rewrite ${name}"
  else
    fail "rewrite ${name}: result differs from a freshly generated file" "$(head -n 20 "${dir}/diff.txt")"
  fi
}

###############################################################################
echo "# rewriteJoomlaComposeIdentity"

#            name                 key    env    sub    domain     mail  secure puid  php   entry named   new key new env new sub new domain
rewrite_case plain                jcb    JCB    jcb    vdm.dev    false false  false false false false  test    TEST    test    vdm.dev
rewrite_case all-features         jcb    JCB    jcb    vdm.dev    true  true   true  true  true  false  clone   CLONE   clone   example.org
rewrite_case same-env-key         abc    ABC    abc    vdm.dev    true  true   false false false false  abd     ABC     abd     vdm.dev
rewrite_case same-sub-new-domain  abc    ABC    abc    vdm.dev    false true   false false false false  abd     ABD     abc     vdm.io
rewrite_case key-db               db     DB     db     vdm.dev    true  true   true  true  true  false  data    DATA    data    vdm.dev
rewrite_case key-joomla           joomla JOOMLA joomla vdm.dev    true  true   true  true  true  false  site    SITE    site    vdm.dev
rewrite_case key-mariadb          mariadb MARIADB mariadb vdm.dev true  true   true  true  true  false  maria   MARIA   maria   vdm.dev
rewrite_case key-prefix           ab     AB     ab     vdm.dev    true  true   true  true  true  false  abc     ABC     abc     vdm.dev
rewrite_case key-suffix           abc    ABC    abc    vdm.dev    true  true   true  true  true  false  ab      AB      ab      vdm.dev
rewrite_case upper-case-key       Jcb    JCB    jcb    vdm.dev    true  true   false false false false  Test    TEST    test    vdm.dev
rewrite_case named-volumes        jcb    JCB    jcb    vdm.dev    true  true   true  false false true   test    TEST    test    vdm.dev
rewrite_case env-key-project      jcb    PROJECT jcb   vdm.dev    true  true   true  true  true  false  test    TEST    test    vdm.dev
rewrite_case bulk-php-ini         abcde  ABCDE  site   vdm.dev    true  true   true  true  false false  test    TEST    test    vdm.dev   bulk

# the shared bulk/php.ini path must survive untouched
if grep -q 'PROJECT_PATH}/bulk/php.ini' "${WORK}/bulk-php-ini/got.yml"; then
  pass "rewrite bulk-php-ini keeps the shared bulk/php.ini mount"
else
  fail "rewrite bulk-php-ini lost the shared bulk/php.ini mount"
fi

# an env key that is a prefix of a global variable must not touch that variable
if grep -q '\${VDM_PROJECT_PATH}/test/joomla' "${WORK}/env-key-project/got.yml"; then
  pass "rewrite env-key-project leaves \${VDM_PROJECT_PATH} alone"
else
  fail "rewrite env-key-project rewrote \${VDM_PROJECT_PATH}"
fi

# a leftover old value must be reported (simulate a hand edit the rules do not cover)
mkdir -p "${WORK}/leftover"
gen_compose jcb JCB jcb vdm.dev false false false false false false >"${WORK}/leftover/old.yml"
echo '      - EXTRA_HOST=mariadbjcb' >>"${WORK}/leftover/old.yml"
rewriteJoomlaComposeIdentity "${WORK}/leftover/old.yml" "${WORK}/leftover/got.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev
rc=$?
if [ "${rc}" -eq 0 ] && ! grep -q 'mariadbjcb' "${WORK}/leftover/got.yml"; then
  pass "rewrite also covers extra lines that use the key"
else
  fail "rewrite extra line: returned ${rc}"
fi
rewriteJoomlaComposeIdentity "${WORK}/leftover/missing.yml" "${WORK}/leftover/got2.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev
rc=$?
[ "${rc}" -eq 1 ] && pass "rewrite returns 1 for a missing source" || fail "rewrite missing source returned ${rc}"

###############################################################################
echo "# getJoomlaComposeIdentity"

gen_compose jcb JCB jcb vdm.dev true true true true true false >"${WORK}/identity.yml"
if getJoomlaComposeIdentity "${WORK}/identity.yml" &&
  [ "${VDM_SRC_KEY}" = "jcb" ] && [ "${VDM_SRC_ENV_KEY}" = "JCB" ] &&
  [ "${VDM_SRC_PROJECT_FOLDER}" = "jcb" ] && [ "${VDM_SRC_MAILCATCHER}" = "true" ] &&
  [ "${VDM_SRC_NAMED_VOLUMES}" = "false" ] && [ "${VDM_SRC_SECURE}" = "true" ]; then
  pass "identity of a full featured container"
else
  fail "identity of a full featured container" "key=${VDM_SRC_KEY} env=${VDM_SRC_ENV_KEY} folder=${VDM_SRC_PROJECT_FOLDER} mail=${VDM_SRC_MAILCATCHER} named=${VDM_SRC_NAMED_VOLUMES} secure=${VDM_SRC_SECURE}"
fi

gen_compose abc ABC abc vdm.dev false false false false false true >"${WORK}/identity-named.yml"
if getJoomlaComposeIdentity "${WORK}/identity-named.yml" &&
  [ "${VDM_SRC_KEY}" = "abc" ] && [ "${VDM_SRC_NAMED_VOLUMES}" = "true" ] &&
  [ "${VDM_SRC_MAILCATCHER}" = "false" ] && [ "${VDM_SRC_SECURE}" = "false" ] && [ -z "${VDM_SRC_PROJECT_FOLDER}" ]; then
  pass "identity of a named volumes container"
else
  fail "identity of a named volumes container" "key=${VDM_SRC_KEY} named=${VDM_SRC_NAMED_VOLUMES} folder=${VDM_SRC_PROJECT_FOLDER}"
fi

printf 'services:\n  web:\n    image: nginx\n' >"${WORK}/hand-written.yml"
if getJoomlaComposeIdentity "${WORK}/hand-written.yml"; then
  fail "identity of a hand written file should fail"
else
  pass "identity of a hand written file returns an error"
fi

###############################################################################
echo "# cloneJoomlaConfiguration"

write_config() {
  cat >"$1" <<'PHP'
<?php
class JConfig {
	public $sitename = 'JCB Site';
	public $dbtype = 'mysqli';
	public $host = 'mariadbjcb:3306';
	public $user = 'vdm_user';
	public $password = 'p@ss\'word';
	public $db = 'vdm_io';
	public $dbprefix = 'jcb_';
	public $mailer = 'smtp';
	public $smtphost = 'mailcatcherjcb';
	public $smtpport = 1025;
	public $secret = 'abcDEF123';
	public $live_site = '';
}
PHP
}

CONFIG="${WORK}/configuration.php"
write_config "${CONFIG}"
chmod 644 "${CONFIG}"
cloneJoomlaConfiguration "${CONFIG}" jcb test "It's a & b | \\ clone"
rc=$?
[ "${rc}" -eq 0 ] && pass "configuration returns 0" || fail "configuration returned ${rc}"
[ "$(getJoomlaConfigValue "${CONFIG}" host)" = "mariadbtest:3306" ] && pass "configuration host patched, port kept" || fail "configuration host is $(getJoomlaConfigValue "${CONFIG}" host)"
[ "$(getJoomlaConfigValue "${CONFIG}" smtphost)" = "mailcatchertest" ] && pass "configuration smtphost patched" || fail "configuration smtphost is $(getJoomlaConfigValue "${CONFIG}" smtphost)"
if grep -qF "public \$sitename = 'It\\'s a & b | \\\\ clone';" "${CONFIG}"; then
  pass "configuration sitename escaped for PHP"
else
  fail "configuration sitename" "$(grep sitename "${CONFIG}")"
fi
[ "$(getJoomlaConfigValue "${CONFIG}" db)" = "vdm_io" ] && pass "configuration db unchanged" || fail "configuration db changed"
[ "$(getJoomlaConfigValue "${CONFIG}" user)" = "vdm_user" ] && pass "configuration user unchanged" || fail "configuration user changed"
grep -qF "public \$password = 'p@ss\\'word';" "${CONFIG}" && pass "configuration password unchanged" || fail "configuration password changed"
[ "$(getJoomlaConfigValue "${CONFIG}" dbprefix)" = "jcb_" ] && pass "configuration dbprefix unchanged" || fail "configuration dbprefix changed"
[ "$(getJoomlaConfigValue "${CONFIG}" secret)" = "abcDEF123" ] && pass "configuration secret unchanged" || fail "configuration secret changed"
[ "$(stat -c '%a' "${CONFIG}" 2>/dev/null || stat -f '%Lp' "${CONFIG}")" = "644" ] && pass "configuration mode kept" || fail "configuration mode changed"

# without a site name the name stays
write_config "${CONFIG}"
cloneJoomlaConfiguration "${CONFIG}" jcb test ''
[ "$(getJoomlaConfigValue "${CONFIG}" sitename)" = "JCB Site" ] && pass "configuration sitename kept when empty" || fail "configuration sitename changed when empty"

# a host without a port
write_config "${CONFIG}"
sed -i.bak "s/mariadbjcb:3306/mariadbjcb/" "${CONFIG}" && rm -f "${CONFIG}.bak"
cloneJoomlaConfiguration "${CONFIG}" jcb test ''
[ "$(getJoomlaConfigValue "${CONFIG}" host)" = "mariadbtest" ] && pass "configuration host without port patched" || fail "configuration host without port is $(getJoomlaConfigValue "${CONFIG}" host)"

# a host of another container must be refused
write_config "${CONFIG}"
cloneJoomlaConfiguration "${CONFIG}" other test ''
rc=$?
[ "${rc}" -eq 2 ] && pass "configuration refuses a foreign database host" || fail "configuration foreign host returned ${rc}"
[ "$(getJoomlaConfigValue "${CONFIG}" host)" = "mariadbjcb:3306" ] && pass "configuration untouched after refusal" || fail "configuration changed after refusal"

cloneJoomlaConfiguration "${WORK}/missing.php" jcb test ''
rc=$?
[ "${rc}" -eq 1 ] && pass "configuration returns 1 for a missing file" || fail "configuration missing file returned ${rc}"

###############################################################################
echo "# cloneContainerEnvVariables / cloneContainerEnvFile / removeContainerEnvVariables"

ENV="${WORK}/.env"
cat >"${ENV}" <<'ENVFILE'
VDM_PROJECT_PATH="/home/x/Projects"
VDM_JCB_DB="vdm_io"
VDM_JCB_DB_USER="vdm_user"
VDM_JCB_DB_PASS="p@ss[word]"
VDM_JCB_DB_ROOT="root&pass"
VDM_JCB_PUID="#1000"
VDM_JCB_PGID="#1000"
VDM_JCB_JOOMLA_DB_PREFIX="jcb_"
VDM_JCB_JOOMLA_ADMIN_PASSWORD="admin"
VDM_JCB_CLI_COMMANDS="extension:list;"
VDM_JCBX_DB="other"
VDM_JCB_UNKNOWN="not copied"
ENVFILE
cp "${ENV}" "${ENV}.orig"
cloneContainerEnvVariables "${ENV}" JCB TEST
rc=$?
[ "${rc}" -eq 0 ] && pass "env copy returns 0" || fail "env copy returned ${rc}"
[ "$(grep -c '^VDM_TEST_' "${ENV}")" -eq 9 ] && pass "env copy added the 9 known values" || fail "env copy added $(grep -c '^VDM_TEST_' "${ENV}") values" "$(grep '^VDM_TEST_' "${ENV}")"
grep -qF 'VDM_TEST_DB_PASS="p@ss[word]"' "${ENV}" && pass "env copy keeps values verbatim" || fail "env copy changed a value"
grep -qF 'VDM_TEST_PUID="#1000"' "${ENV}" && pass "env copy keeps the uid marker" || fail "env copy lost the uid marker"
grep -q '^VDM_TEST_UNKNOWN' "${ENV}" && fail "env copy copied an unknown suffix" || pass "env copy skips unknown suffixes"
[ "$(grep -c '^VDM_JCBX_DB=' "${ENV}")" -eq 1 ] && pass "env copy leaves other keys alone" || fail "env copy touched another key"
cloneContainerEnvVariables "${ENV}" JCB TEST
[ "$(grep -c '^VDM_TEST_' "${ENV}")" -eq 9 ] && pass "env copy is idempotent" || fail "env copy duplicated values"
cloneContainerEnvVariables "${ENV}" JCB JCB
[ "$(grep -c '^VDM_JCB_' "${ENV}")" -eq 10 ] && pass "env copy with the same key is a no-op" || fail "env copy with the same key changed the file"
removeContainerEnvVariables "${ENV}" TEST
if diff -q "${ENV}.orig" "${ENV}" >/dev/null; then
  pass "env remove restores the original file"
else
  fail "env remove left differences" "$(diff "${ENV}.orig" "${ENV}")"
fi

# env key PROJECT must not drag VDM_PROJECT_PATH along
printf 'VDM_PROJECT_PATH="/p"\nVDM_PROJECT_DB="db"\n' >"${WORK}/.env2"
cloneContainerEnvVariables "${WORK}/.env2" PROJECT NEW
if grep -q '^VDM_NEW_DB="db"' "${WORK}/.env2" && ! grep -q '^VDM_NEW_PATH' "${WORK}/.env2"; then
  pass "env copy with key PROJECT leaves VDM_PROJECT_PATH alone"
else
  fail "env copy with key PROJECT" "$(cat "${WORK}/.env2")"
fi

# per-container env file
cloneContainerEnvFile "${ENV}.orig" "${WORK}/.env3" JCB TEST
if [ "$(grep -c '^VDM_TEST_' "${WORK}/.env3")" -eq 9 ] && ! grep -q '^VDM_JCB_DB=' "${WORK}/.env3" &&
  grep -q '^VDM_JCB_UNKNOWN=' "${WORK}/.env3" && grep -q '^VDM_PROJECT_PATH=' "${WORK}/.env3"; then
  pass "env file copy renames the known values and keeps the rest"
else
  fail "env file copy" "$(cat "${WORK}/.env3")"
fi
[ "$(stat -c '%a' "${WORK}/.env3" 2>/dev/null || stat -f '%Lp' "${WORK}/.env3")" = "600" ] && pass "env file copy is mode 600" || fail "env file copy mode"
cloneContainerEnvFile "${ENV}.orig" "${WORK}/.env4" JCB JCB
diff -q "${ENV}.orig" "${WORK}/.env4" >/dev/null && pass "env file copy with the same key is identical" || fail "env file copy with the same key differs"

###############################################################################
echo
echo "passed: ${PASSED}  failed: ${FAILED}"
[ "${FAILED}" -eq 0 ]
