#!/usr/bin/env bash
#
# Tests for the Joomla container clone helpers in src/octojoom.
#
# The helpers have no user interaction, so they are extracted from the script
# and run against fixtures generated by the script's own joomlaContainer
# template. Run from anywhere:
#
#   bash tests/test-clone.sh
#
# Needs bash 4+, sed, grep, awk and diff. No docker or whiptail required.
#
# SC2015: "A && pass || fail" is the intended check idiom (pass never fails).
# SC2016: single quoted ${...} are literal compose variables we grep for.
# SC2034: the VDM_* values are read by the extracted joomlaContainer template.
# shellcheck disable=SC2015,SC2016,SC2034

set -u

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="${TEST_DIR}/../src/octojoom"
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

PASSED=0
FAILED=0

pass() {
  PASSED=$((PASSED + 1))
  echo "ok   - $1"
}

fail() {
  FAILED=$((FAILED + 1))
  echo "FAIL - $1"
  [ -n "${2:-}" ] && echo "       $2"
}

# extract one function definition from the script
extract_function() {
  awk -v name="$1" '$0 ~ "^function "name"\\(\\) \\{$" {p=1} p {print} p && /^}$/ {p=0; exit}' "${SCRIPT}"
}

for fn in getYMLine1 getYMLine2 getYMLine3 joomlaContainer runPrivileged getDialogHeight \
  getJoomlaEnvSuffixes getEscapedRegex getJoomlaComposeIdentity rewriteJoomlaComposeIdentity \
  getJoomlaConfigValue cloneJoomlaConfiguration cloneContainerEnvVariables \
  hasContainerEnvVariables cloneContainerEnvFile removeContainerEnvVariables \
  isJoomlaHostInUse; do
  src=$(extract_function "${fn}")
  if [ -z "${src}" ]; then
    echo "FAIL - function ${fn} not found in ${SCRIPT}"
    exit 1
  fi
  eval "${src}"
done

###############################################################################
# fixture generator: builds a docker-compose.yml the way joomla__TRuST__setup does
# $1 key  $2 env key  $3 sub-domain  $4 domain
# $5 mailcatcher (true/false)  $6 secure (true/false)  $7 puid (true/false)
# $8 php.ini (true/false)  $9 entrypoint (true/false)  $10 named volumes (true/false)
# $11 (optional) php.ini project folder (default: the key)
gen_compose() {
  local mail="${5:-false}" secure="${6:-false}" puid="${7:-false}"
  local php="${8:-false}" entry="${9:-false}" named="${10:-false}"
  local php_folder="${11:-$1}"
  local middlewares='joomla-security'
  VDM_KEY="$1"
  VDM_ENV_KEY="$2"
  VDM_SUBDOMAIN="$3"
  VDM_DOMAIN="$4"
  VDM_J_REPO='joomla'
  VDM_JV='5.3'
  VDM_TRAEFIK_GATEWAY='traefik_webgateway'
  VDM_PUID=''
  VDM_PGID=''
  ${puid} && VDM_PUID=1000 && VDM_PGID=1000
  VDM_JOOMLA_SECURE_LABELS=''
  VDM_PHPMYADMIN_SECURE_LABELS=''
  VDM_EXTRA_CONTAINER_STUFF=''
  VDM_EXTRA_JOOMLA_ENV=''
  VDM_VOLUMES=''
  if ${secure}; then
    VDM_JOOMLA_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.joomla${VDM_KEY}.entrypoints=websecure\"")
    VDM_JOOMLA_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.joomla${VDM_KEY}.tls.certresolver=vdmresolver\"")
    VDM_JOOMLA_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.joomla${VDM_KEY}.service=joomla${VDM_KEY}\"")
    VDM_JOOMLA_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.joomla${VDM_KEY}.middlewares=${middlewares}\"")
    VDM_JOOMLA_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.services.joomla${VDM_KEY}.loadbalancer.server.port=80\"")
    VDM_PHPMYADMIN_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.phpmyadmin${VDM_KEY}.entrypoints=websecure\"")
    VDM_PHPMYADMIN_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.phpmyadmin${VDM_KEY}.tls.certresolver=vdmresolver\"")
    VDM_PHPMYADMIN_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.phpmyadmin${VDM_KEY}.service=phpmyadmin${VDM_KEY}\"")
    VDM_PHPMYADMIN_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.routers.phpmyadmin${VDM_KEY}.middlewares=${middlewares}\"")
    VDM_PHPMYADMIN_SECURE_LABELS+=$(getYMLine3 "- \"traefik.http.services.phpmyadmin${VDM_KEY}.loadbalancer.server.port=80\"")
  fi
  if ${named}; then
    VDM_JOOMLA_VOLUMES_MOUNT=$(getYMLine3 "- ${VDM_KEY,,}_web:/var/www/html")
    VDM_DB_VOLUMES_MOUNT=$(getYMLine3 "- ${VDM_KEY,,}_db:/var/lib/mysql")
    VDM_VOLUMES='volumes:'
    VDM_VOLUMES+=$(getYMLine1 "${VDM_KEY,,}_web:")
    VDM_VOLUMES+=$(getYMLine1 "${VDM_KEY,,}_db:")
  else
    VDM_JOOMLA_VOLUMES_MOUNT=$(getYMLine3 "- \"\${VDM_PROJECT_PATH}/${VDM_KEY}/joomla:/var/www/html\"")
    VDM_DB_VOLUMES_MOUNT=$(getYMLine3 "- \"\${VDM_PROJECT_PATH}/${VDM_KEY}/db:/var/lib/mysql\"")
  fi
  if ${mail}; then
    VDM_EXTRA_CONTAINER_STUFF=$(getYMLine1 "mailcatcher${VDM_KEY}:")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine2 "image: schickling/mailcatcher")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine2 "container_name: mailcatcher${VDM_KEY}")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine2 "restart: unless-stopped")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine2 "networks:")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- traefik")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine2 "labels:")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "# mailcatcher")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.enable=true\"")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.http.routers.mailcatcher${VDM_KEY}.rule=Host(\`${VDM_SUBDOMAIN}mail.${VDM_DOMAIN}\`)\"")
    if ${secure}; then
      VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.http.routers.mailcatcher${VDM_KEY}.entrypoints=websecure\"")
      VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.http.routers.mailcatcher${VDM_KEY}.tls.certresolver=vdmresolver\"")
    fi
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.http.routers.mailcatcher${VDM_KEY}.service=mailcatcher${VDM_KEY}\"")
    VDM_EXTRA_CONTAINER_STUFF+=$(getYMLine3 "- \"traefik.http.services.mailcatcher${VDM_KEY}.loadbalancer.server.port=1080\"")
    VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_SMTP_HOST=mailcatcher${VDM_KEY}:1025")
  fi
  # auto deploy values
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_DB_TYPE=\${VDM_${VDM_ENV_KEY^^}_JOOMLA_DB_TYPE}")
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_DB_PREFIX=\${VDM_${VDM_ENV_KEY^^}_JOOMLA_DB_PREFIX}")
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_SITE_NAME=\${VDM_${VDM_ENV_KEY^^}_JOOMLA_SITE_NAME}")
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_ADMIN_PASSWORD=\${VDM_${VDM_ENV_KEY^^}_JOOMLA_ADMIN_PASSWORD}")
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_EXTENSIONS_URLS=\${VDM_${VDM_ENV_KEY^^}_EXTENSIONS_URLS}")
  VDM_EXTRA_JOOMLA_ENV+=$(getYMLine3 "- JOOMLA_CLI_COMMANDS=\${VDM_${VDM_ENV_KEY^^}_CLI_COMMANDS}")
  if ${php}; then
    VDM_JOOMLA_VOLUMES_MOUNT+=$(getYMLine3 "- \"\${VDM_PROJECT_PATH}/${php_folder}/php.ini:/var/www/html/php.ini\"")
  fi
  if ${entry}; then
    VDM_JOOMLA_VOLUMES_MOUNT+=$(getYMLine3 "- \"\${VDM_PROJECT_PATH}/${VDM_KEY}/entrypoint.sh:/entrypoint.sh\"")
  fi
  joomlaContainer
}

# run one rewrite case and compare with a freshly generated file
# $1 name  $2..$11 see gen_compose for the old values  $12 new key  $13 new env  $14 new sub  $15 new domain
rewrite_case() {
  local name="$1"
  local old_key="$2" old_env="$3" old_sub="$4" old_domain="$5"
  local mail="$6" secure="$7" puid="$8" php="$9" entry="${10}" named="${11}"
  local new_key="${12}" new_env="${13}" new_sub="${14}" new_domain="${15}"
  local php_folder="${16:-}"
  local dir="${WORK}/${name}"
  local rc
  mkdir -p "${dir}"
  gen_compose "${old_key}" "${old_env}" "${old_sub}" "${old_domain}" "${mail}" "${secure}" "${puid}" "${php}" "${entry}" "${named}" "${php_folder:-$old_key}" >"${dir}/old.yml"
  gen_compose "${new_key}" "${new_env}" "${new_sub}" "${new_domain}" "${mail}" "${secure}" "${puid}" "${php}" "${entry}" "${named}" "${php_folder:-$new_key}" >"${dir}/expected.yml"
  rewriteJoomlaComposeIdentity "${dir}/old.yml" "${dir}/got.yml" "${old_key}" "${new_key}" "${old_env}" "${new_env}" "${old_sub}" "${new_sub}" "${old_domain}" "${new_domain}"
  rc=$?
  if [ "${rc}" -ne 0 ]; then
    fail "rewrite ${name}: returned ${rc}"
  elif diff -u "${dir}/expected.yml" "${dir}/got.yml" >"${dir}/diff.txt"; then
    pass "rewrite ${name}"
  else
    fail "rewrite ${name}: result differs from a freshly generated file" "$(head -n 20 "${dir}/diff.txt")"
  fi
}

###############################################################################
echo "# rewriteJoomlaComposeIdentity"

#            name                 key    env    sub    domain     mail  secure puid  php   entry named   new key new env new sub new domain
rewrite_case plain                jcb    JCB    jcb    vdm.dev    false false  false false false false  test    TEST    test    vdm.dev
rewrite_case all-features         jcb    JCB    jcb    vdm.dev    true  true   true  true  true  false  clone   CLONE   clone   example.org
rewrite_case same-env-key         abc    ABC    abc    vdm.dev    true  true   false false false false  abd     ABC     abd     vdm.dev
rewrite_case same-sub-new-domain  abc    ABC    abc    vdm.dev    false true   false false false false  abd     ABD     abc     vdm.io
rewrite_case key-db               db     DB     db     vdm.dev    true  true   true  true  true  false  data    DATA    data    vdm.dev
rewrite_case key-joomla           joomla JOOMLA joomla vdm.dev    true  true   true  true  true  false  site    SITE    site    vdm.dev
rewrite_case key-mariadb          mariadb MARIADB mariadb vdm.dev true  true   true  true  true  false  maria   MARIA   maria   vdm.dev
rewrite_case key-prefix           ab     AB     ab     vdm.dev    true  true   true  true  true  false  abc     ABC     abc     vdm.dev
rewrite_case key-suffix           abc    ABC    abc    vdm.dev    true  true   true  true  true  false  ab      AB      ab      vdm.dev
rewrite_case upper-case-key       Jcb    JCB    jcb    vdm.dev    true  true   false false false false  Test    TEST    test    vdm.dev
rewrite_case named-volumes        jcb    JCB    jcb    vdm.dev    true  true   true  false false true   test    TEST    test    vdm.dev
rewrite_case env-key-project      jcb    PROJECT jcb   vdm.dev    true  true   true  true  true  false  test    TEST    test    vdm.dev
rewrite_case bulk-php-ini         abcde  ABCDE  site   vdm.dev    true  true   true  true  false false  test    TEST    test    vdm.dev   bulk
rewrite_case key-in-domain        site   SITE   www    joomlasite.com true true false false false false  shop    SHOP    shop    joomlasite.com
rewrite_case key-in-subdomain     jcb    JCB    joomlajcb vdm.dev true  true   false false false false  test    TEST    test    vdm.dev
rewrite_case key-in-new-domain    jcb    JCB    jcb    vdm.dev    true  true   false false false false  test    TEST    shop    joomlajcb.dev

# a source that mounts a project folder other than its key (hand edited, or a renamed folder)
mkdir -p "${WORK}/mount-folder"
gen_compose jcb JCB jcb vdm.dev true true true true true false |
  sed 's#PROJECT_PATH}/jcb/#PROJECT_PATH}/legacy/#g' >"${WORK}/mount-folder/old.yml"
gen_compose test TEST test vdm.dev true true true true true false >"${WORK}/mount-folder/expected.yml"
rewriteJoomlaComposeIdentity "${WORK}/mount-folder/old.yml" "${WORK}/mount-folder/got.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev legacy
rc=$?
if [ "${rc}" -eq 0 ] && diff -q "${WORK}/mount-folder/expected.yml" "${WORK}/mount-folder/got.yml" >/dev/null; then
  pass "rewrite moves the mounts of a differently named project folder to the new key"
else
  fail "rewrite mount-folder: returned ${rc}" "$(diff "${WORK}/mount-folder/expected.yml" "${WORK}/mount-folder/got.yml" | head -n 10)"
fi
# without the folder the rewrite must refuse instead of keeping the source's mounts
rewriteJoomlaComposeIdentity "${WORK}/mount-folder/old.yml" "${WORK}/mount-folder/got2.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev
rc=$?
[ "${rc}" -eq 2 ] && pass "rewrite refuses when the source mounts stay unknown" || fail "rewrite unknown mount folder returned ${rc}"

# a host that is not one of the source's hosts (hand added) must not be copied silently
mkdir -p "${WORK}/extra-host"
gen_compose jcb JCB jcb vdm.dev false true false false false false |
  sed 's/rule=Host(`jcb.vdm.dev`)/rule=Host(`jcb.vdm.dev`) || Host(`www.customer.com`)/' >"${WORK}/extra-host/old.yml"
rewriteJoomlaComposeIdentity "${WORK}/extra-host/old.yml" "${WORK}/extra-host/got.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev
rc=$?
[ "${rc}" -eq 2 ] && pass "rewrite refuses a hand added host it cannot rename" || fail "rewrite extra host returned ${rc}"

# mounts written in a way the rewrite cannot rename must stop it, never be copied as they are
for variant in unbraced absolute long-syntax; do
  mkdir -p "${WORK}/mount-${variant}"
  gen_compose jcb JCB jcb vdm.dev false false false false false false >"${WORK}/mount-${variant}/old.yml"
  case "${variant}" in
  unbraced) sed -i.bak 's#"${VDM_PROJECT_PATH}/jcb/db:#"$VDM_PROJECT_PATH/jcb/db:#' "${WORK}/mount-${variant}/old.yml" ;;
  absolute) sed -i.bak 's#"${VDM_PROJECT_PATH}/jcb/db:#"/srv/data/jcb/db:#' "${WORK}/mount-${variant}/old.yml" ;;
  long-syntax) printf '      - type: bind\n        source: /srv/data/jcb/db\n        target: /var/lib/mysql\n' >>"${WORK}/mount-${variant}/old.yml" ;;
  esac
  rm -f "${WORK}/mount-${variant}/old.yml.bak"
  rewriteJoomlaComposeIdentity "${WORK}/mount-${variant}/old.yml" "${WORK}/mount-${variant}/got.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev
  rc=$?
  [ "${rc}" -eq 2 ] && pass "rewrite refuses a ${variant} database mount" || fail "rewrite ${variant} database mount returned ${rc}"
done

# an old mount left commented out above the moved one: the active mount is the one that counts
mkdir -p "${WORK}/mount-commented"
gen_compose jcb JCB jcb vdm.dev false false false false false false |
  awk '/^ *- "\$\{VDM_PROJECT_PATH\}\/jcb\/(db|joomla):/ {
    old = $0; sub(/- /, "# - ", old); print old
    new = $0; sub(/\/jcb\//, "/legacy/", new); print new
    next
  } { print }' >"${WORK}/mount-commented/old.yml"
getJoomlaComposeIdentity "${WORK}/mount-commented/old.yml"
[ "${VDM_SRC_PROJECT_FOLDER}" = "legacy" ] && pass "identity ignores a commented old mount" || fail "identity took folder ${VDM_SRC_PROJECT_FOLDER} from a comment"
rewriteJoomlaComposeIdentity "${WORK}/mount-commented/old.yml" "${WORK}/mount-commented/got.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev "${VDM_SRC_PROJECT_FOLDER}"
rc=$?
if [ "${rc}" -eq 0 ] && grep -v '^ *#' "${WORK}/mount-commented/got.yml" | grep -q 'PROJECT_PATH}/test/db:/var/lib/mysql' &&
  ! grep -v '^ *#' "${WORK}/mount-commented/got.yml" | grep -q 'legacy'; then
  pass "rewrite moves the active mounts when an old one is commented out"
else
  fail "rewrite commented mount: returned ${rc}" "$(grep -n 'PROJECT_PATH' "${WORK}/mount-commented/got.yml")"
fi
# the same file, with the folder taken from the comment as the old code did, must be refused
rewriteJoomlaComposeIdentity "${WORK}/mount-commented/old.yml" "${WORK}/mount-commented/got2.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev jcb
rc=$?
[ "${rc}" -eq 2 ] && pass "rewrite refuses when the active mounts stay on another folder" || fail "rewrite stale folder returned ${rc}"

# host rules the rewrite cannot rename must stop it
for variant in double-quotes two-hosts regexp; do
  mkdir -p "${WORK}/host-${variant}"
  gen_compose jcb JCB jcb vdm.dev false false false false false false >"${WORK}/host-${variant}/old.yml"
  case "${variant}" in
  double-quotes) sed -i.bak 's/rule=Host(`jcb.vdm.dev`)/rule=Host(\\"jcb.vdm.dev\\")/' "${WORK}/host-${variant}/old.yml" ;;
  two-hosts) sed -i.bak 's/rule=Host(`jcb.vdm.dev`)/rule=Host(`jcb.vdm.dev`, `www.jcb.vdm.dev`)/' "${WORK}/host-${variant}/old.yml" ;;
  regexp) sed -i.bak 's/rule=Host(`jcb.vdm.dev`)/rule=HostRegexp(`^jcb[.]vdm[.]dev$`)/' "${WORK}/host-${variant}/old.yml" ;;
  esac
  rm -f "${WORK}/host-${variant}/old.yml.bak"
  rewriteJoomlaComposeIdentity "${WORK}/host-${variant}/old.yml" "${WORK}/host-${variant}/got.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev
  rc=$?
  [ "${rc}" -eq 2 ] && pass "rewrite refuses a ${variant} host rule" || fail "rewrite ${variant} host rule returned ${rc}"
done

# a sub-domain typed with capitals is still the clone's own host
rewrite_case mixed-case-sub     jcb    JCB    jcb    vdm.dev    true  true   false false false false  test    TEST    Test    vdm.dev

# the rewrite never touches the router name of another service on a Host line
if grep -q 'routers.joomlashop.rule=Host(`shop.joomlasite.com`)' "${WORK}/key-in-domain/got.yml"; then
  pass "rewrite key-in-domain renames the router and keeps the domain"
else
  fail "rewrite key-in-domain router line" "$(grep 'rule=Host' "${WORK}/key-in-domain/got.yml")"
fi

# the shared bulk/php.ini path must survive untouched
if grep -q 'PROJECT_PATH}/bulk/php.ini' "${WORK}/bulk-php-ini/got.yml"; then
  pass "rewrite bulk-php-ini keeps the shared bulk/php.ini mount"
else
  fail "rewrite bulk-php-ini lost the shared bulk/php.ini mount"
fi

# an env key that is a prefix of a global variable must not touch that variable
if grep -q '\${VDM_PROJECT_PATH}/test/joomla' "${WORK}/env-key-project/got.yml"; then
  pass "rewrite env-key-project leaves \${VDM_PROJECT_PATH} alone"
else
  fail "rewrite env-key-project rewrote \${VDM_PROJECT_PATH}"
fi

# a leftover old value must be reported (simulate a hand edit the rules do not cover)
mkdir -p "${WORK}/leftover"
gen_compose jcb JCB jcb vdm.dev false false false false false false >"${WORK}/leftover/old.yml"
echo '      - EXTRA_HOST=mariadbjcb' >>"${WORK}/leftover/old.yml"
rewriteJoomlaComposeIdentity "${WORK}/leftover/old.yml" "${WORK}/leftover/got.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev
rc=$?
if [ "${rc}" -eq 0 ] && ! grep -q 'mariadbjcb' "${WORK}/leftover/got.yml"; then
  pass "rewrite also covers extra lines that use the key"
else
  fail "rewrite extra line: returned ${rc}"
fi
rewriteJoomlaComposeIdentity "${WORK}/leftover/missing.yml" "${WORK}/leftover/got2.yml" jcb test JCB TEST jcb test vdm.dev vdm.dev
rc=$?
[ "${rc}" -eq 1 ] && pass "rewrite returns 1 for a missing source" || fail "rewrite missing source returned ${rc}"

###############################################################################
echo "# getJoomlaComposeIdentity"

gen_compose jcb JCB jcb vdm.dev true true true true true false >"${WORK}/identity.yml"
if getJoomlaComposeIdentity "${WORK}/identity.yml" &&
  [ "${VDM_SRC_KEY}" = "jcb" ] && [ "${VDM_SRC_ENV_KEY}" = "JCB" ] &&
  [ "${VDM_SRC_PROJECT_FOLDER}" = "jcb" ] && [ "${VDM_SRC_MAILCATCHER}" = "true" ] &&
  [ "${VDM_SRC_NAMED_VOLUMES}" = "false" ] && [ "${VDM_SRC_SECURE}" = "true" ]; then
  pass "identity of a full featured container"
else
  fail "identity of a full featured container" "key=${VDM_SRC_KEY} env=${VDM_SRC_ENV_KEY} folder=${VDM_SRC_PROJECT_FOLDER} mail=${VDM_SRC_MAILCATCHER} named=${VDM_SRC_NAMED_VOLUMES} secure=${VDM_SRC_SECURE}"
fi

gen_compose abc ABC abc vdm.dev false false false false false true >"${WORK}/identity-named.yml"
if getJoomlaComposeIdentity "${WORK}/identity-named.yml" &&
  [ "${VDM_SRC_KEY}" = "abc" ] && [ "${VDM_SRC_NAMED_VOLUMES}" = "true" ] &&
  [ "${VDM_SRC_MAILCATCHER}" = "false" ] && [ "${VDM_SRC_SECURE}" = "false" ] && [ -z "${VDM_SRC_PROJECT_FOLDER}" ]; then
  pass "identity of a named volumes container"
else
  fail "identity of a named volumes container" "key=${VDM_SRC_KEY} named=${VDM_SRC_NAMED_VOLUMES} folder=${VDM_SRC_PROJECT_FOLDER}"
fi

printf 'services:\n  web:\n    image: nginx\n' >"${WORK}/hand-written.yml"
if getJoomlaComposeIdentity "${WORK}/hand-written.yml"; then
  fail "identity of a hand written file should fail"
else
  pass "identity of a hand written file returns an error"
fi

###############################################################################
echo "# cloneJoomlaConfiguration"

write_config() {
  cat >"$1" <<'PHP'
<?php
class JConfig {
	public $sitename = 'JCB Site';
	public $dbtype = 'mysqli';
	public $host = 'mariadbjcb:3306';
	public $user = 'vdm_user';
	public $password = 'p@ss\'word';
	public $db = 'vdm_io';
	public $dbprefix = 'jcb_';
	public $mailer = 'smtp';
	public $smtphost = 'mailcatcherjcb';
	public $smtpport = 1025;
	public $secret = 'abcDEF123';
	public $live_site = '';
}
PHP
}

CONFIG="${WORK}/configuration.php"
write_config "${CONFIG}"
chmod 644 "${CONFIG}"
cloneJoomlaConfiguration "${CONFIG}" jcb test "It's a & b | \\ clone"
rc=$?
[ "${rc}" -eq 0 ] && pass "configuration returns 0" || fail "configuration returned ${rc}"
[ "$(getJoomlaConfigValue "${CONFIG}" host)" = "mariadbtest:3306" ] && pass "configuration host patched, port kept" || fail "configuration host is $(getJoomlaConfigValue "${CONFIG}" host)"
[ "$(getJoomlaConfigValue "${CONFIG}" smtphost)" = "mailcatchertest" ] && pass "configuration smtphost patched" || fail "configuration smtphost is $(getJoomlaConfigValue "${CONFIG}" smtphost)"
if grep -qF "public \$sitename = 'It\\'s a & b | \\\\ clone';" "${CONFIG}"; then
  pass "configuration sitename escaped for PHP"
else
  fail "configuration sitename" "$(grep sitename "${CONFIG}")"
fi
[ "$(getJoomlaConfigValue "${CONFIG}" db)" = "vdm_io" ] && pass "configuration db unchanged" || fail "configuration db changed"
[ "$(getJoomlaConfigValue "${CONFIG}" user)" = "vdm_user" ] && pass "configuration user unchanged" || fail "configuration user changed"
grep -qF "public \$password = 'p@ss\\'word';" "${CONFIG}" && pass "configuration password unchanged" || fail "configuration password changed"
[ "$(getJoomlaConfigValue "${CONFIG}" dbprefix)" = "jcb_" ] && pass "configuration dbprefix unchanged" || fail "configuration dbprefix changed"
[ "$(getJoomlaConfigValue "${CONFIG}" secret)" = "abcDEF123" ] && pass "configuration secret unchanged" || fail "configuration secret changed"
[ "$(stat -c '%a' "${CONFIG}" 2>/dev/null || stat -f '%Lp' "${CONFIG}")" = "644" ] && pass "configuration mode kept" || fail "configuration mode changed"

# without a site name the name stays
write_config "${CONFIG}"
cloneJoomlaConfiguration "${CONFIG}" jcb test ''
[ "$(getJoomlaConfigValue "${CONFIG}" sitename)" = "JCB Site" ] && pass "configuration sitename kept when empty" || fail "configuration sitename changed when empty"

# a host without a port
write_config "${CONFIG}"
sed -i.bak "s/mariadbjcb:3306/mariadbjcb/" "${CONFIG}" && rm -f "${CONFIG}.bak"
cloneJoomlaConfiguration "${CONFIG}" jcb test ''
[ "$(getJoomlaConfigValue "${CONFIG}" host)" = "mariadbtest" ] && pass "configuration host without port patched" || fail "configuration host without port is $(getJoomlaConfigValue "${CONFIG}" host)"

# a host of another container must be refused
write_config "${CONFIG}"
cloneJoomlaConfiguration "${CONFIG}" other test ''
rc=$?
[ "${rc}" -eq 2 ] && pass "configuration refuses a foreign database host" || fail "configuration foreign host returned ${rc}"
[ "$(getJoomlaConfigValue "${CONFIG}" host)" = "mariadbjcb:3306" ] && pass "configuration untouched after refusal" || fail "configuration changed after refusal"

cloneJoomlaConfiguration "${WORK}/missing.php" jcb test ''
rc=$?
[ "${rc}" -eq 1 ] && pass "configuration returns 1 for a missing file" || fail "configuration missing file returned ${rc}"

###############################################################################
echo "# cloneContainerEnvVariables / cloneContainerEnvFile / removeContainerEnvVariables"

ENV="${WORK}/.env"
cat >"${ENV}" <<'ENVFILE'
VDM_PROJECT_PATH="/home/x/Projects"
VDM_JCB_DB="vdm_io"
VDM_JCB_DB_USER="vdm_user"
VDM_JCB_DB_PASS="p@ss[word]"
VDM_JCB_DB_ROOT="root&pass"
VDM_JCB_PUID="#1000"
VDM_JCB_PGID="#1000"
VDM_JCB_JOOMLA_DB_PREFIX="jcb_"
VDM_JCB_JOOMLA_ADMIN_PASSWORD="admin"
VDM_JCB_CLI_COMMANDS="extension:list;"
VDM_JCBX_DB="other"
VDM_JCB_UNKNOWN="not copied"
ENVFILE
cp "${ENV}" "${ENV}.orig"
ADDED=$(cloneContainerEnvVariables "${ENV}" JCB TEST)
rc=$?
[ "${rc}" -eq 0 ] && pass "env copy returns 0" || fail "env copy returned ${rc}"
[ "$(grep -c '^VDM_TEST_' "${ENV}")" -eq 9 ] && pass "env copy added the 9 known values" || fail "env copy added $(grep -c '^VDM_TEST_' "${ENV}") values" "$(grep '^VDM_TEST_' "${ENV}")"
[ "$(printf '%s\n' "${ADDED}" | grep -c '^VDM_TEST_')" -eq 9 ] && pass "env copy reports the 9 names it added" || fail "env copy reported" "${ADDED}"
hasContainerEnvVariables "${ENV}" TEST && pass "env key TEST is now in use" || fail "env key TEST not reported in use"
hasContainerEnvVariables "${ENV}" JCBX && pass "env key JCBX is in use" || fail "env key JCBX not reported in use"
hasContainerEnvVariables "${ENV}" NONE && fail "env key NONE reported in use" || pass "env key NONE is free"
grep -qF 'VDM_TEST_DB_PASS="p@ss[word]"' "${ENV}" && pass "env copy keeps values verbatim" || fail "env copy changed a value"
grep -qF 'VDM_TEST_PUID="#1000"' "${ENV}" && pass "env copy keeps the uid marker" || fail "env copy lost the uid marker"
grep -q '^VDM_TEST_UNKNOWN' "${ENV}" && fail "env copy copied an unknown suffix" || pass "env copy skips unknown suffixes"
[ "$(grep -c '^VDM_JCBX_DB=' "${ENV}")" -eq 1 ] && pass "env copy leaves other keys alone" || fail "env copy touched another key"
AGAIN=$(cloneContainerEnvVariables "${ENV}" JCB TEST)
[ "$(grep -c '^VDM_TEST_' "${ENV}")" -eq 9 ] && [ -z "${AGAIN}" ] && pass "env copy is idempotent" || fail "env copy duplicated values"
cloneContainerEnvVariables "${ENV}" JCB JCB >/dev/null
[ "$(grep -c '^VDM_JCB_' "${ENV}")" -eq 10 ] && pass "env copy with the same key is a no-op" || fail "env copy with the same key changed the file"
mapfile -t NAMES <<<"${ADDED}"
removeContainerEnvVariables "${ENV}" "${NAMES[@]}"
if diff -q "${ENV}.orig" "${ENV}" >/dev/null; then
  pass "env remove restores the original file"
else
  fail "env remove left differences" "$(diff "${ENV}.orig" "${ENV}")"
fi
[ "$(stat -c '%a' "${ENV}" 2>/dev/null || stat -f '%Lp' "${ENV}")" = "600" ] && pass "env remove leaves the file mode 600" || fail "env remove file mode"
ls "${ENV}".?????? >/dev/null 2>&1 && fail "env remove left a temp file" || pass "env remove leaves no temp file"

# a value the clone did not add survives the rollback
printf 'VDM_NEW_PUID="#1000"\nVDM_OLD_DB="db"\nVDM_OLD_PUID="#2000"\n' >"${WORK}/.env5"
ADDED=$(cloneContainerEnvVariables "${WORK}/.env5" OLD NEW)
mapfile -t NAMES <<<"${ADDED}"
removeContainerEnvVariables "${WORK}/.env5" "${NAMES[@]}"
if grep -qx 'VDM_NEW_PUID="#1000"' "${WORK}/.env5" && ! grep -q '^VDM_NEW_DB=' "${WORK}/.env5"; then
  pass "env remove only removes what the clone added"
else
  fail "env remove removed a value it did not add" "$(cat "${WORK}/.env5")"
fi
removeContainerEnvVariables "${WORK}/.env5" && pass "env remove without names is a no-op" || fail "env remove without names failed"

# a shared env file without a final new line must not get glued lines
printf 'VDM_JCB_DB="x"\nVDM_JCB_DB_USER="u"' >"${WORK}/.env6"
cloneContainerEnvVariables "${WORK}/.env6" JCB TEST >/dev/null
if [ "$(wc -l <"${WORK}/.env6")" -eq 4 ] && grep -qx 'VDM_JCB_DB_USER="u"' "${WORK}/.env6" &&
  grep -qx 'VDM_TEST_DB="x"' "${WORK}/.env6" && grep -qx 'VDM_TEST_DB_USER="u"' "${WORK}/.env6"; then
  pass "env copy into a file without a final new line"
else
  fail "env copy into a file without a final new line" "$(cat -A "${WORK}/.env6" 2>/dev/null || cat "${WORK}/.env6")"
fi

# env key PROJECT must not drag VDM_PROJECT_PATH along
printf 'VDM_PROJECT_PATH="/p"\nVDM_PROJECT_DB="db"\n' >"${WORK}/.env2"
cloneContainerEnvVariables "${WORK}/.env2" PROJECT NEW >/dev/null
if grep -q '^VDM_NEW_DB="db"' "${WORK}/.env2" && ! grep -q '^VDM_NEW_PATH' "${WORK}/.env2"; then
  pass "env copy with key PROJECT leaves VDM_PROJECT_PATH alone"
else
  fail "env copy with key PROJECT" "$(cat "${WORK}/.env2")"
fi

# per-container env file
cloneContainerEnvFile "${ENV}.orig" "${WORK}/.env3" JCB TEST
if [ "$(grep -c '^VDM_TEST_' "${WORK}/.env3")" -eq 9 ] && ! grep -q '^VDM_JCB_DB=' "${WORK}/.env3" &&
  grep -q '^VDM_JCB_UNKNOWN=' "${WORK}/.env3" && grep -q '^VDM_PROJECT_PATH=' "${WORK}/.env3"; then
  pass "env file copy renames the known values and keeps the rest"
else
  fail "env file copy" "$(cat "${WORK}/.env3")"
fi
[ "$(stat -c '%a' "${WORK}/.env3" 2>/dev/null || stat -f '%Lp' "${WORK}/.env3")" = "600" ] && pass "env file copy is mode 600" || fail "env file copy mode"
cloneContainerEnvFile "${ENV}.orig" "${WORK}/.env4" JCB JCB
diff -q "${ENV}.orig" "${WORK}/.env4" >/dev/null && pass "env file copy with the same key is identical" || fail "env file copy with the same key differs"

###############################################################################
echo "# isJoomlaHostInUse / getDialogHeight"

VDM_REPO_PATH="${WORK}/repo"
mkdir -p "${VDM_REPO_PATH}/joomla/available/demo.vdm.dev" "${VDM_REPO_PATH}/portainer"
gen_compose demo DEMO demo vdm.dev true false false false false false >"${VDM_REPO_PATH}/joomla/available/demo.vdm.dev/docker-compose.yml"
printf '      - "traefik.http.routers.portainer.rule=Host(`port.vdm.dev`)"\n' >"${VDM_REPO_PATH}/portainer/docker-compose.yml"
isJoomlaHostInUse demo.vdm.dev && pass "host of a Joomla site is in use" || fail "host demo.vdm.dev not found"
isJoomlaHostInUse demodb.vdm.dev && pass "phpmyadmin host is in use" || fail "host demodb.vdm.dev not found"
isJoomlaHostInUse demomail.vdm.dev && pass "mailcatcher host is in use" || fail "host demomail.vdm.dev not found"
isJoomlaHostInUse port.vdm.dev && pass "portainer host is in use" || fail "host port.vdm.dev not found"
isJoomlaHostInUse demo.vdm.io && fail "host demo.vdm.io reported in use" || pass "host on another domain is free"
isJoomlaHostInUse emo.vdm.dev && fail "host emo.vdm.dev reported in use" || pass "a host is matched whole, not as a suffix"

SHORT='one\ntwo\nthree'
LONG="$(printf '%0300d' 0)"
[ "$(TERM=dumb getDialogHeight "${SHORT}" 8 2>/dev/null)" -ge 11 ] && pass "dialog height fits three lines" || fail "dialog height for three lines"
[ "$(TERM=dumb getDialogHeight "${LONG}" 8 2>/dev/null)" -ge 11 ] && pass "dialog height counts wrapped lines" || fail "dialog height for a wrapped line"

###############################################################################
echo
echo "passed: ${PASSED}  failed: ${FAILED}"
[ "${FAILED}" -eq 0 ]
